 SELECT
    to_char(r.BDATE, 'DD.MM.YYYY') day,
    a.FULLNAME ORGANIZATION ,
    rf.CODE  otchet,
    bi.CODE  pokazatel,
    CASE WHEN STRVAL IS NOT NULL THEN STRVAL
	 WHEN NUMVAL  IS NOT NULL THEN CAST(NUMVAL  AS varchar(30))
	 WHEN DATEVAL IS NOT NULL THEN CAST(DATEVAL AS varchar(30))
	    ELSE NULL END value
	FROM PARUS.BLINDEXVALUES  d
		INNER JOIN PARUS.BLSUBREPORTS s
		ON (d.PRN = s.RN)
		INNER JOIN PARUS.BLREPORTS r
		ON(s.PRN = r.RN)
		INNER JOIN PARUS.AGNLIST a
		on(r.AGENT = a.rn)
		INNER JOIN PARUS.BLREPFORMED pf
		on(r.BLREPFORMED = pf.RN)
		INNER JOIN PARUS.BLREPFORM rf
		on(pf.PRN = rf.RN)
		INNER JOIN PARUS.BALANCEINDEXES bi
		on(d.BALANCEINDEX = bi.RN)
		WHERE rf.CODE = '4.2 COVID 19'
		and r.BDATE = trunc(SYSDATE)
